[package]
authors = ["Chaoqian Xu <chaoranxu@gmail.com>"]
edition = "2021"
name = "maxwell-frontend"
version = "0.5.0"

[dependencies]
config = "0.13.3"
log = "0.4.20"
log4rs = "1.2.0"

actix = "0.13.0"
actix-http = "3.3.1"
actix-web = "4.3.1"
actix-web-actors = "4.2.0"
futures-intrusive = "0.5.0"
tokio = {version = "1.32.0", features = ["full"]}

ahash = "0.8.3"
anyhow = "1.0.75"
bytes = "1.4.0"
dashmap = "5.5.1"
dycovec = "0.1.1"
evmap = "10.0.2"
fxhash = "0.2.1"
indexmap = "2.0.0"
once_cell = "1.18.0"
prost = "0.11.9"
quick_cache = "0.3.0"
serde = "1.0.185"
serde_derive = "1.0.185"

maxwell-protocol = {git = "https://github.com/maxwell-dev/maxwell-protocol-rust.git", tag = "v0.13.1"}
maxwell-utils = {git = "https://github.com/maxwell-dev/maxwell-utils-rust.git", tag = "v0.9.12"}
# maxwell-utils = {path = "../../maxwell-utils-impls/maxwell-utils-rust"}
